FROM python:3.7.4
#RUN apt update -y && apt install xclip xsel -y
#RUN apt update -y && apt install xclip python3-pyqt4 -y
RUN apt update -y && apt install curl -y
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt install nodejs -y
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8888
RUN jupyter labextension install @jupyterlab/github @jupyterlab/google-drive jupyterlab-drawio
RUN pip install jupyterlab-git && jupyter serverextension enable --py jupyterlab_git
ENTRYPOINT jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root